name: sync-branch-release
on:
  push:
    branches:
      - 'release-*'
jobs:
  sync-branch:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Merge release-* -> develop
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          head_to_merge: ${{ github.ref }}
          target_branch: develop
          github_token: ${{ secrets.GH_REPO }}
