name: sync-branch-master
on:
  push:
    branches:
      - 'master'
jobs:
  sync-branch:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Merge master -> develop
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          head_to_merge: master
          target_branch: develop
          github_token: ${{ secrets.GH_REPO }}
